### ISSUE TITLE
Downgrade to an older of Fluxnetworks

### ISSUE THREAD

**Issue by RobinNightWing** [VoyageGamingNetwork/tiny_planets#16]
There’s a bug with the current of Fluxnetworks. Downgrading to an older one might prove to be a temporary solution

**Comment by Nimtrod** [comment]
Can you link me to the issue? Or tell me what the issue is?

**Comment by RobinNightWing** [comment]
Making a private or restricted network is broken

**Comment by Nimtrod** [comment]
From the 3.0.15 Patchnotes
Fixed issue connecting/creating to Private networks

So we will update to that version :) ty!

**Comment by RobinNightWing** [comment]
Thank god
