### ISSUE TITLE
Crafting problem

### ISSUE THREAD

**Issue by Goreator** [VoyageGamingNetwork/tiny_planets#19]
The emerald armor from Tiny Progressions and from Actually Additions has the same crafting recipes.

The problem is when you craft the armor you just get the Actually Additions one. But I want the armor from Tiny Progressions because I want to craft the magma armor.
plz fix thx.

**Comment by Nimtrod** [comment]
You can just press the small button next to the output: [Click me!](https://streamable.com/sck6w)
